### PR TITLE
DOC-2216 Documentation for improved config-update workflow

### PR DESCRIPTION
**Pull request by colintg**
### Ticket links
- DOC ticket link: https://graphsql.atlassian.net/browse/DOC-2216
- Feature ticket link: https://graphsql.atlassian.net/browse/TP-4820

### What was done
- Updated command glossary to reflect the new arg `--restart-deps` for `gadmin config apply`

### CODE REVIEW

**Comment by colintg** [comment]
Hi @victorleeTG @arunramasami I'm wondering if there is a need to include the troubleshooting doc for this feature? If there is, where is the best place for me to put it? Thank you!

**Review by arun-TG-PM — APPROVED** [review]

**Review by victorleeTG — COMMENTED** [review]
1) This seems to be trying to merge to the wrong DOC product version.
APPS-2729 says it is for **tg_3.10.0**.
This PR is trying to merge to DOC branch **4.1.o**

2) The topic does not match the DOC ticket
APPS-2729 is about TLS.
DOC-2211 is about RUN QUERY and INTERPRET QUERY options.
3) Please DO NOT lump in unrelated changes (e.g. OS version support, options for CONFIG APPLY.) This is a bad practice.

File: modules/release-notes/pages/index.adoc [hunk 1]
```diff
@@ -170,6 +170,9 @@ See xref:tigergraph-server:user-access:rbac-row-policy/row-policy-privlages-tabl
 * Fixed issue where incorrect error response occurred when specified graph does not exist (APS-2824).
 * Fixed issue where users encountered error `Vertex expansion failed: c.default.post is not a function` during Explore Neighbors operation in Insight (APS-2840).
 
+==== Security
+* Enhanced security by disabling unapproved SSL/TLS protocols of `DHE-RSA-AES128-GCM-SHA256` and `DHE-RSA-AES256-GCM-SHA384` and upgrading to TLS 1.3 in Nginx (APPS-2729).
+
```
Comment (victorleeTG) [inline modules/release-notes/pages/index.adoc]:
```suggestion
```
This is from an unrelated issue in tg_3.10.0. This release notes page is from 3.10.0. I don't know how/why Git thinks this is the 4.1.0 release notes page, because it isn't.

**Review by victorleeTG — APPROVED** [review]
This PR had the wrong DOC ticket number (2211). Changed it to 2216.
